<?php
/**
 * @package Abricos
 * @subpackage Botask
 * @copyright 2012-2016 Alexander Kuzmin
 * @license http://opensource.org/licenses/mit-license.php MIT License
 * @author Alexander Kuzmin <roosit@abricos.org>
 */

class BotaskType {
    const TASK = 0;
    const PROJECT = 1;
    const FOLDER = 2;
}


/**
 * Статус задачи
 */
class BotaskStatus {

    /**
     * Открытая задача
     *
     * @var integer
     */
    const TASK_OPEN = 1;

    /**
     * Открытая задача повторно
     *
     * @var integer
     */
    const TASK_REOPEN = 2;

    /**
     * Завершенная (закрытая) задача
     *
     * @var integer
     */
    const TASK_CLOSE = 3;

    /**
     * Задача в работе. Принятая самостоятельно.
     *
     * @var integer
     */
    const TASK_ACCEPT = 4;

    /**
     * Задача в работе. Назначенная конкретному лицу.
     *
     * @var integer
     */
    const TASK_ASSIGN = 5;

    /**
     * Задача удалена.
     *
     * @var integer
     */
    const TASK_REMOVE = 6;

    /**
     * Задача в архиве.
     *
     * @var integer
     */
    const TASK_ARHIVE = 7;
}


/**
 * Class BotaskTask
 *
 * @property int $parentid
 * @property int $iType
 * @property int $userid
 * @property int $iStatus
 * @property int $statusDate
 * @property string $title
 * @property string $descript
 * @property int $date
 * @property int $updateDate
 * @property int $removeDate
 * @property int $deadline
 * @property bool $deadlineTime
 * @property BotaskUserRoleList $users
 * @property BotaskResolutionInTaskList $resolutions
 * @property BotaskFileList $files
 * @property BotaskImageList $images
 * @property BotaskCheckList $checks
 */
class BotaskTask extends AbricosModel {
    protected $_structModule = 'botask';
    protected $_structName = 'Task';

    private $_commentOwner;

    public function GetCommentOwner(){
        if (!empty($this->_commentOwner)){
            return $this->_commentOwner;
        }
        return $this->_commentOwner = Abricos::GetApp('comment')->InstanceClass('Owner', array(
            "module" => "botask",
            "type" => "task",
            "ownerid" => $this->id
        ));
    }

}

/**
 * Class BotaskTaskList
 *
 * @method BotaskTask Get(int $id)
 * @method BotaskTask GetByIndex(int $i)
 */
class BotaskTaskList extends AbricosModelList {

    public $lastHistoryId = 0;

    /**
     * @param CommentStatisticList $list
     */
    public function SetCommentStatistics($list){
        $cnt = $list->Count();
        for ($i = 0; $i < $cnt; $i++){
            $stat = $list->GetByIndex($i);
            $task = $this->Get($stat->id);
            if (empty($task)){
                continue; // what is it? %)
            }
            $task->commentStatistic = $stat;
        }
    }

    public function ToJSON(){
        $ret = parent::ToJSON(); // TODO: Change the autogenerated stub
        $ret->lastHistoryId = $this->lastHistoryId;
        return $ret;
    }
}

/**
 * Class BotaskUserRole
 */
class BotaskUserRole extends AbricosModel {
    protected $_structModule = 'botask';
    protected $_structName = 'UserRole';
}

class BotaskUserRoleList extends AbricosModelList {
}

class BotaskResolution extends AbricosModel {
    protected $_structModule = 'botask';
    protected $_structName = 'Resolution';
}

class BotaskResolutionList extends AbricosModelList {
}

class BotaskResolutionInTask extends AbricosModel {
    protected $_structModule = 'botask';
    protected $_structName = 'ResolutionInTask';
}

class BotaskResolutionInTaskList extends AbricosModelList {
}

class BotaskFile extends AbricosModel {
    protected $_structModule = 'botask';
    protected $_structName = 'File';
}

class BotaskFileList extends AbricosModelList {
}

class BotaskImage extends AbricosModel {
    protected $_structModule = 'botask';
    protected $_structName = 'Image';
}

class BotaskImageList extends AbricosModelList {
}

class BotaskCheck extends AbricosModel {
    protected $_structModule = 'botask';
    protected $_structName = 'Check';
}

class BotaskCheckList extends AbricosModelList {
}

/**
 * Class BotaskHistory
 *
 * @property int $taskid
 * @property int $userid
 * @property int $date
 *
 * @property int $iParentStatus
 * @property int $iStatus
 * @property int $statusUserId
 *
 * @property int $parentid
 * @property bool $parentChanged
 *
 * @property int $priority
 * @property bool $priorityChanged
 *
 * @property string $title
 * @property bool $titleChanged
 *
 * @property string $body
 * @property bool $bodyChanged
 * 
 * @property string $imageData
 * @property bool $imageDataChanged
 *
 * @property string $checks
 * @property bool $checksChanged
 *
 * @property int $deadline
 * @property bool $deadlineChanged
 *
 * @property int $deadlineByTime
 * @property bool $deadlineByTimeChanged
 *
 * @property string $userAdded
 * @property string $userRemoved
 */
class BotaskHistory extends AbricosModel {
    protected $_structModule = 'botask';
    protected $_structName = 'History';

}

class BotaskHistoryList extends AbricosModelList {
}
